# Use the official Node.js 16 image.
FROM node:16
    
# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your application's code
COPY . .

# Expose the port the app runs on
EXPOSE 8080

# Command to run your app
CMD [ "node", "app.js" ]